name: Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        permissions:
            contents: read
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            VITE_SUPABASE_PROJECT_ID: ${{ secrets.VITE_SUPABASE_PROJECT_ID }}
            VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Create .env file
              run: |
                  echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
                  echo "VITE_SUPABASE_PROJECT_ID=${{ secrets.VITE_SUPABASE_PROJECT_ID }}" >> .env
                  echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build
              env:
                  GENERATE_SOURCEMAP: false

            - name: Sitemap Generation
              run: cd src/utils && node generate-sitemap.mjs
              # If site generaton fails, continue to deploy
              continue-on-error: true

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload to GitHub Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  path: build/

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
